# Definition

**In MATLAB, an *array* is a rectangular block of numbers. Special meaning is attached to 1-by-1 arrays, which are *scalars*, and to arrays with only one row or column, which are *vectors*.**

To be coherent with the mathematical definition of a *matrix*, a *matrix* is an array with 2 dimensions. The online documentation uses *matrix* instead of *array*.

# Array basics

## Entering arrays

A array can be entered as an explicit list of elements:

- Seperate the elements of a row with blanks or commas.
- Use a semicolon, `;`, or insert `enter` to indicate the end of each row.
- Surround the entire list of elements with square brackets, `[ ]`.

In [1]:
A = [16, 3, 2, 13; 5, 10, 11, 8; 9, 6, 7, 12; 4, 15, 14, 1]
B = [16 3 2 13
     5 10 11 8
     9 6 7 12
     4 15 14 1]

A =

   16    3    2   13
    5   10   11    8
    9    6    7   12
    4   15   14    1

B =

   16    3    2   13
    5   10   11    8
    9    6    7   12
    4   15   14    1



## Magic square

The array `A` is a magic square: if you take the sum along any row or column, or along either of the two main diagonals, you will always get the samber number.

The function `sum` returns the sum of each of the columns:

In [2]:
sum(A)

ans =

   34   34   34   34



To get the sum of each of the rows, a second argument indicating the dimension has to be added to the function `sum`:

In [3]:
sum(A, 2)

ans =

   34
   34
   34
   34



The same vector can be found by evaluating the `sum` function on the transpose of the array:

In [4]:
sum(A')'

ans =

   34
   34
   34
   34



The operator `'` can be replaced by the function `transpose`:

In [5]:
transpose(sum(transpose(A)))

ans =

   34
   34
   34
   34



The sum of the elements on the main diagonal is obtained with the `sum` and the `diag` function:

In [6]:
sum(diag(A))

ans =  34


The other diagonal can be found by the function `fliplr`, that flips an array from left to right:

In [7]:
sum(diag(fliplr(A)))

ans =  34


|Function|Description|
|:---|:---|
|`sum(A)`|the sum of the elements of `A` along the first array dimension whose size does not equal 1|
|`sum(A,dim)`|the sum along dimension `dim`|
|`cumsum(A)`|the cumulative sum of `A` along the first array dimension in A whose size does not equal 1|
|`cumsum(A,dim)`|the cumulative sum of `A` along dimension `dim`
|`diff(A)`|the difference of the elements of `A` along the first array dimension whose size does not equal 1|
|`prod(A)`|the product of the elements of `A` along the first array dimension whose size does not equal 1|
|`prod(A,dim)`|the product along dimension `dim`|
|`cumprod(A)`|the cumulative product of `A` along the first array dimension in A whose size does not equal 1|
|`cumprod(A,dim)`|the cumulative product of `A` along dimension `dim`|
|`transpose(A)=A'`|the transpose of `A`|
|`diag(A)`|a column vector of the main diagonal elements of `A`|
|`diag(A,k)`|a column vector of the elements on the `k`th diagonal of `A`|
|`fliplr(A)`|an array with the columns of `A` flipped from left to right|
|`flipud(A)`|an array with the rows of `A` flippes from up to down|

## Subscripts

The element in row `i` and column `j` of `A` is denoted by `A(i,j)`. Eg. `A(4,2)` is the number in the fourth row and second column:

In [8]:
A
A(4,2)

A =

   16    3    2   13
    5   10   11    8
    9    6    7   12
    4   15   14    1

ans =  15


It is also possible to refer to the elements of an array with a single subscript, `A(k)`. Eg. `A(8)` is another way of referring to the value `15` stored in `A(4,2)`:

In [9]:
k = 8;
j = ceil(k / 4)
i = k - 4 * (j-1)
A(k) == A(i,j)

j =  2
i =  4
ans =  1


If you try to use the value of an element outside of the array, it is an error:

In [10]:
A(5,4)

error: A(I,J): row index out of bounds; value 5 out of bound 4


On the other hand, if you store a value in an element outside of the array, the size increases to accommodate the new element:

In [11]:
X = A;
X(4,5) = 17

X =

   16    3    2   13    0
    5   10   11    8    0
    9    6    7   12    0
    4   15   14    1   17



## The colon operator

The colon, `:`, is one of the most important MATLAB operators. It occurs in several different forms.

The expression `1:10` is a row vector containing the integers from 1 to 10:

In [12]:
1:10

ans =

    1    2    3    4    5    6    7    8    9   10



To obtain nonunit spacing, specify an increment. Eg.

In [13]:
100:-7:50

ans =

   100    93    86    79    72    65    58    51



In [14]:
0:pi/4:pi

ans =

    0.00000    0.78540    1.57080    2.35619    3.14159



Subscript expressions involving colons refer to portions of an array, eg.

In [15]:
A
A(1:4,4)
A(3, 2:3)
A(:)'

A =

   16    3    2   13
    5   10   11    8
    9    6    7   12
    4   15   14    1

ans =

   13
    8
   12
    1

ans =

   6   7

ans =

 Columns 1 through 15:

   16    5    9    4    3   10    6   15    2   11    7   14   13    8   12

 Column 16:

    1



## Generating matrices

MATLAB provides five functions that generate basic arrays:

|Function|Description|
|:---|:---|
|`zeros(m,n)`|all zeros|
|`ones(m,n)`|all ones|
|`rand(m,n)`|uniformly distributed random elements in the interval $[0,1]$|
|`randn(m,n)`|normally distributed random elements|
|`diag(v)`|a square diagonal matrix with the elements of vector `v` on the main diagonal|

In [16]:
Z = zeros(2,4)
R = rand(1,5)
D = diag(randn(2,1))

Z =

   0   0   0   0
   0   0   0   0

R =

   0.073866   0.849421   0.719887   0.216177   0.117672

D =

Diagonal Matrix

   0.91541         0
         0   1.26040



## Concatenation

*Concatenation* is the process of joining small array to make bigger ones. In fact, entering an array is a concatenation of its individual elements. The pair of square brackets,`[ ]`, is the concatenation operator. Eg.

In [17]:
B = [A, A+32; A+48, A+16]

B =

   16    3    2   13   48   35   34   45
    5   10   11    8   37   42   43   40
    9    6    7   12   41   38   39   44
    4   15   14    1   36   47   46   33
   64   51   50   61   32   19   18   29
   53   58   59   56   21   26   27   24
   57   54   55   60   25   22   23   28
   52   63   62   49   20   31   30   17



## Deleting rows and columns

A row or a column can be deleted from an array using just a pair of empty square brackets.

In [18]:
X = A;
X(:,2) = []

X =

   16    2   13
    5   11    8
    9    7   12
    4   14    1



If you delete an single element from an array, the result is not an array anymore:

In [19]:
X(1,2) = []

error: a null assignment can only have one non-colon index


However, using a single subscript deletes a single element or sequence of elements, and reshapes the remaining elements into a row vector:

In [20]:
X(2:2:10) = [];
X'

ans =

   16    9    2    7   13   12    1



## Dimensions

MATLAB provides two functions that return the dimensions of a array: `length` and `size`:

|Statement|Description|
|:--|:--|
|`l = length(A)`| the length of the largest array dimension in `A`|
|`sz = size(A)`| a row vector whose elements contain the length of the corresponding dimension of `A`|
|`szdim = size(A,dim)`| the length of dimension `dim`|
|`[m,n] = size(A)`| the number of rows and columns when `A` is a matrix|

In [21]:
lz = length(Z)
lr = length(R)
lrn = length(D)
sz = size(Z)
szdim = size(Z,1)
[m,n]=size(Z)

lz =  4
lr =  5
lrn =  2
sz =

   2   4

szdim =  2
m =  2
n =  4


## Reshaping an array

The function `reshape(A, dim1, dim2, ...)` creates a new array with dimensions `dim1`, `dim2`, ... and as elements the values of A, eg.

In [22]:
reshape(1:10, 5, 2)
reshape(A, 2, 8)

ans =

    1    6
    2    7
    3    8
    4    9
    5   10

ans =

   16    9    3    6    2    7   13   12
    5    4   10   15   11   14    8    1



# Array operations

## Operators

The following list of operators execute on an element-by-element base:

|Operator|Description|
|:---|:---|
|`A+B`|Addition|
|`A-B`|Subtraction|
|`A.*B`|Element-by-element multiplication|
|`A./B`|Element-by-element division|
|`A.^B`|Element-by-element power|

`A` and `B` having the same dimensions. Eg.

In [23]:
A.*A

ans =

   256     9     4   169
    25   100   121    64
    81    36    49   144
    16   225   196     1



## Scalar expansion

Arrays and scalars can be combined in several different ways. Eg., a scalar is subtracted from a matrix by subtracting it from each element:

In [24]:
B = A - 8.5

B =

   7.50000  -5.50000  -6.50000   4.50000
  -3.50000   1.50000   2.50000  -0.50000
   0.50000  -2.50000  -1.50000   3.50000
  -4.50000   6.50000   5.50000  -7.50000



With scalar expansion, MATLAB assigns a specified scalar to all indices in a range. Eg.

In [25]:
B(1:2,2:3)=0

B =

   7.50000   0.00000   0.00000   4.50000
  -3.50000   0.00000   0.00000  -0.50000
   0.50000  -2.50000  -1.50000   3.50000
  -4.50000   6.50000   5.50000  -7.50000



## Building arrays

Array operations are useful for building other arrays:

In [26]:
n = (0:9)';
pows = [n n.^2 2.^n]

pows =

     0     0     1
     1     1     2
     2     4     4
     3     9     8
     4    16    16
     5    25    32
     6    36    64
     7    49   128
     8    64   256
     9    81   512



## Mathematical functions

The elementary mathematical functions of Lecture 1 operate all on arrays element-by-element:

In [27]:
x = (1:0.1:2)';
logs = [x log10(x)]

logs =

   1.00000   0.00000
   1.10000   0.04139
   1.20000   0.07918
   1.30000   0.11394
   1.40000   0.14613
   1.50000   0.17609
   1.60000   0.20412
   1.70000   0.23045
   1.80000   0.25527
   1.90000   0.27875
   2.00000   0.30103

