# Definition

**In MATLAB, a *matrix* is a rectangular array of number. Special meaning is attached to 1-by-1 matrices, which are *scalars*, and to matrices with only one row or column, which are *vectors*.**

# Entering matrices

A matrix can be entered as an explicit list of elements:

- Seperate the elements of a row with blanks or commas.
- Use a semicolon, `;`, or insert `enter` to indicate the end of each row.
- Surround the entire list of elements with square brackets, `[ ]`.

In [1]:
A = [16, 3, 2, 13; 5, 10, 11, 8; 9, 6, 7, 12; 4, 15, 14, 1]
B = [16 3 2 13
     5 10 11 8
     9 6 7 12
     4 15 14 1]

A =

   16    3    2   13
    5   10   11    8
    9    6    7   12
    4   15   14    1

B =

   16    3    2   13
    5   10   11    8
    9    6    7   12
    4   15   14    1



# Magic square

The matrix `A` is a magic square: if you take the sum along any row or column, or along either of the two main diagonals, you will always get the samber number.

The function `sum` returns the sum of each of the columns:

In [2]:
sum(A)

ans =

   34   34   34   34



To get the sum of each of the rows, a second argument indicating the dimension has to be added to the function `sum`:

In [3]:
sum(A, 2)

ans =

   34
   34
   34
   34



The same vector can be found by evaluating the `sum` function on the transpose of the matrix:

In [4]:
sum(A')'

ans =

   34
   34
   34
   34



The operator `'` can be replaced by the function `transpose`:

In [5]:
transpose(sum(transpose(A)))

ans =

   34
   34
   34
   34



The sum of the elements on the main diagonal is obtained with the `sum` and the `diag` function:

In [6]:
sum(diag(A))

ans =  34


The other diagonal can be found by the function `fliplr`, that flips a matrix from left to right:

In [7]:
sum(diag(fliplr(A)))

ans =  34


# Subscripts

The element in row `i` and column `j` of `A` is denoted by `A(i,j)`. Eg. `A(4,2)` is the number in the fourth row and second column:

In [8]:
A
A(4,2)

A =

   16    3    2   13
    5   10   11    8
    9    6    7   12
    4   15   14    1

ans =  15


It is also possible to refer to the elements of a matrix with a single subscript, `A(k)`. Eg. `A(8)` is another way of referring to the value `15` stored in `A(4,2)`:

In [22]:
k = 13
j = ceil(k / 4)
i = k - 4 * (j-1)
A(k) == A(i,j)

k =  13
j =  4
i =  1
ans =  1


If you try to use the value of an element outside of the matrix, it is an error:

In [10]:
A(5,4)

error: A(I,J): row index out of bounds; value 5 out of bound 4


On the other hand, if you store a value in an element outside of the matrix, the size increases to accommodate the new element:

In [11]:
X = A;
X(4,5) = 17

X =

   16    3    2   13    0
    5   10   11    8    0
    9    6    7   12    0
    4   15   14    1   17



# The colon operator

The colon, `:`, is one of the most important MATLAB operators. It occurs in several different forms.

The expression `1:10` is a row vector containing the integers from 1 to 10:

In [12]:
1:10

ans =

    1    2    3    4    5    6    7    8    9   10



To obtain nonunit spacing, specify an increment. Eg.

In [13]:
100:-7:50

ans =

   100    93    86    79    72    65    58    51



In [14]:
0:pi/4:pi

ans =

    0.00000    0.78540    1.57080    2.35619    3.14159



Subscript expressions involving colons refer to portions of a matrix. Eg.

In [15]:
A
A(1:4,4)
A(3, 2:3)

A =

   16    3    2   13
    5   10   11    8
    9    6    7   12
    4   15   14    1

ans =

   13
    8
   12
    1

ans =

   6   7



# Generating matrices

MATLAB provides four functions that generate basic matrices:

|Function|Description|
|:---|:---|
|`zeros(m,n)`|all zeros|
|`ones(m,n)`|all ones|
|`rand(m,n)`|uniformly distributed random elements in the interval $[0,1]$|
|`randn(m,n)`|normally distributed random elements|

In [16]:
Z = zeros(2,4)
F = ones(3,3)
R = rand(1,5)
N = randn(2,1)

Z =

   0   0   0   0
   0   0   0   0

F =

   1   1   1
   1   1   1
   1   1   1

R =

   0.56201   0.28665   0.11383   0.78958   0.36597

N =

  -1.38586
   0.99166



# Dimensions

MATLAB provides two functions that return the dimensions of a matrix: `length` and `size`:

|Statement|Description|
|:--|:--|
|`l = length(A)`| the length of the largest array dimension in `A`|
|`sz = size(A)`| a row vector whose elements contain the length of the corresponding dimension of `A`|
|`szdim = size(A,dim)`| the length of dimension `dim`|
|`[m,n] = size(A)`| the number of rows and columns when `A` is a matrix|

In [17]:
lz = length(Z)
lr = length(R)
lrn = length(N)
sz = size(Z)
szdim = size(Z,1)
[m,n]=size(Z)

lz =  4
lr =  5
lrn =  2
sz =

   2   4

szdim =  2
m =  2
n =  4


# Concatenation