# Logical expressions

## Logical operators

MATLAB has the following logical operators:

- `==`: equal to
- `~=`: not equal to
- `<`: less than
- `>`: greater than
- `<=`: less than or equal
- `>=`: greater than or equal
- `&`: and
- `|`: or

returning an array of the same size having as values `0` or `1`.

In [1]:
b = [3 2 1 4 -4 -7 6]
b > 2
(b >= 1) & (b < 4)
(b <= 3) & (b > 0) | (b > 4)

b =

   3   2   1   4  -4  -7   6

ans =

  1  0  0  1  0  0  1

ans =

  1  1  1  0  0  0  0

ans =

  1  1  1  0  0  0  1



## `find`

The command `find` returns an array containing the indices of values that satisfy a logical operation, eg.

In [2]:
b = [3 2 1 4 -4 -7 6]
find(b > 2)
find((b >= 1) & (b < 4))
find((b <= 3) & (b > 0) | (b > 4))

b =

   3   2   1   4  -4  -7   6

ans =

   1   4   7

ans =

   1   2   3

ans =

   1   2   3   7



To select the elements of an array satisfying a logical operator we combine `find` with array selection:

In [12]:
b = [3 2 1 4 -4 -7 6]
b(find(b > 2))
b(find((b >= 1) & (b < 4)))
b(find((b <= 3) & (b > 0) | (b > 4)))

b =

   3   2   1   4  -4  -7   6

ans =

   3   4   6

ans =

   3   2   1

ans =

   3   2   1   6



## `isequal`

The proper way to check for equality between two variables is the `isequal` command, eg.

In [4]:
a = [1 2 3];
b = [1, 2, 3];
c = [1; 2; 3];
a == b
a == c
isequal(a, b)
isequal(a, c)

ans =

  1  1  1

ans =

  1  0  0
  0  1  0
  0  0  1

ans = 1
ans = 0


## Helper functions

These functions are helpful for reducing the results of matrix comparisons to scalar conditions:

- `isempty`: returns 1 if array is empty, otherwise 0
- `all`: returns 1 if all elements are different from 0, otherwise 0
- `any`: return 1 if an element is different from 0, otherwise 0

In [5]:
isempty([])
isempty(1)
all(ones(3, 1))
all([1 0 3])
any([1 0 3])
any(zeros(3, 1))

ans = 1
ans = 0
ans = 1
ans = 0
ans = 1
ans = 0


# Branching

The `if` statement evaluates a logical expression and executes a group of statements when the expressions is *true*. The optional `elseif` and `else` keywords provide for the execution of alternate groups of statements. And `end` keyword, which matches the `if`, terminates the last group of statements.

Eg., the leap day falls in the Gregorian calendar on 29 February and occurs when the year is divisible by 4, but not by 100 - unless the year is divisible by 400:

In [6]:
year = 2017
if (mod(year, 4) == 0) & ((mod(year, 100) ~= 0) | (mod(year, 400) == 0))
    disp('Leap year');
    C = 1;
else
    disp('No leap year');
    C = 2;
end
C

year =  2017
No leap year
C =  2


Or we can do this with nested `if` statements: 

In [7]:
year = 2017
if mod(year, 4) == 0
    if mod(year, 100) ~= 0
        disp('Leap year');
        C = 1;
    else
        if mod(year, 400) == 0
            disp('Leap year');
            C = 2;
        else
            disp('No leap year');
            C = 3;
        end
    end
else
    disp('No leap year');
    C = 4;
end
C

year =  2017
No leap year
C =  4


It is a good idea to indent the branches for readability, especially when they are nested!

If `A` and `B` are scalars, the following statements will never reach the *unexpected situation*. But for most pairs of matrices, none of the conditions is true for all elements and so the `else` clause is executed:

In [8]:
A = [1]
B = [2]
if A > B
    disp('greater');
elseif A < B
    disp('less');
elseif A == B
    disp('equal');
else
    error('Unexpected situation');
end

A =  1
B =  2
less


# Loops

## `for`

A `for` loop repeats a group of statements a fixed predermined number of times. A matching `end` delineates the statements, eg.:

In [9]:
clear x
x(1) = 0;
x(2) = 1;
for n = 3:10
    x(n) = x(n-1)+x(n-2);
end
disp(x)

    0    1    1    2    3    5    8   13   21   34


It is a good idea to indent the loops for readability, especially when they are nested, eg.:

In [10]:
m = 3;
n = 4;
for i = 1:m
    for j = 1:n
        H(i,j) = 1/(i+j);
    end
end
disp(H)

   0.50000   0.33333   0.25000   0.20000
   0.33333   0.25000   0.20000   0.16667
   0.25000   0.20000   0.16667   0.14286


## `while`

The `while` loop repeats a group of statements an indefinite number of times until a logicial condition is no longer satisfied. A matching `end` delineates the statements, eg.:

In [11]:
clear x
x(1) = 0;
x(2) = 1;
while x(end-1) + x(end) < 1000
    x(end + 1) = x(end) + x(end - 1);
end
disp(x) 

 Columns 1 through 13:

     0     1     1     2     3     5     8    13    21    34    55    89   144

 Columns 14 through 17:

   233   377   610   987


## `continue`

The `continue` statement passes control to the next iteration of the `for` loop or `while` loop in which it appears, skipping any remaining statements in the body of the loop, eg.:

In [16]:
clear x y
x(1) = 0;
x(2) = 1;
y(1) = 0;
while x(end-1) + x(end) < 1000
    x(end + 1) = x(end) + x(end - 1);
    if mod(x(end), 2) ~= 0
        continue
    end
    y(end + 1) = x(end);
end
disp(y)

     0     2     8    34   144   610


## `break`

A `break` statement lets you exit early from a `for` loop or `while` loop. In nested loops, `break` exits from the innermost loop only. Eg.:

In [17]:
clear x
x(1) = 0;
x(2) = 1;
for n = 3:1000
    x(n) = x(n-1)+x(n-2);
    if x(n) + x(n-1) > 1000
        break
    end
end
disp(x)

 Columns 1 through 13:

     0     1     1     2     3     5     8    13    21    34    55    89   144

 Columns 14 through 17:

   233   377   610   987
